version: '3'
services:
  # cochroachDB
  db:
    image: cockroachdb/cockroach:v2.0.1
    command: start --insecure --store=attrs=ssd,path=/var/lib/cockroach/
    restart: always
    volumes:
      - data:/var/lib/cockroach
    expose:
      - "8080"
      - "26257"
    ports:
      - "26257:26257"
      - "8080:8080"
    labels:
      SERVICE_TAGS: production
      SERVICE_NAME: db

  # nakama
  server:
    image: heroiclabs/nakama:2.0.0
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
          /nakama/nakama migrate up --database.address root@cockroachdb:26257 &&
          /nakama/nakama --name nakama1 --database.address root@cockroachdb:26257
    restart: always
    links:
      - "db:db"
    depends_on:
      - db
    volumes:
      - ./:/nakama/data
    expose:
      - "7350"
      - "7351"
    ports:
      - "7350:7350"
      - "7351:7351"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      SERVICE_TAGS: production
      SERVICE_NAME: server
volumes:
  data:
